"""
SQLAlchemy ORM models for the Academic Paper Repository & Recommendation System.

Tables:
    - User            : accounts & auth records
    - Paper           : 9 metadata fields + validation + precomputed vectors
    - PersonalLibrary : join table linking users to papers they've saved
"""

from datetime import datetime

from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    Boolean,
    DateTime,
    ForeignKey,
    UniqueConstraint,
)

from sqlalchemy.orm import relationship, declarative_base


Base = declarative_base()


class User(Base):
    __tablename__ = "users"

    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    username = Column(
        String(100),
        unique=True,
        nullable=False,
        index=True,
    )

    email = Column(
        String(150),
        unique=True,
        nullable=False,
        index=True,
    )

    password_hash = Column(
        String(255),
        nullable=False,
    )

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    library_entries = relationship(
        "PersonalLibrary",
        back_populates="user",
        cascade="all, delete-orphan",
    )

    def __repr__(self):
        return (
            f"<User id={self.id} "
            f"username={self.username!r}>"
        )


class Paper(Base):
    __tablename__ = "papers"

    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # ---------------------------------------------------------
    # 9 core metadata fields
    # ---------------------------------------------------------
    # These fields follow the thesis specification.

    title = Column(
        String(500),
        nullable=False,
    )

    author = Column(
        String(300),
        nullable=True,
    )

    abstract = Column(
        Text,
        nullable=True,
    )

    keywords = Column(
        Text,
        nullable=True,
    )
    # Stores author-provided or YAKE-generated keywords.
    # Example:
    # "machine learning, recommendation system, text mining"

    publication_year = Column(
        Integer,
        nullable=True,
    )

    doi = Column(
        String(100),
        nullable=True,
    )

    subject_category = Column(
        String(200),
        nullable=True,
    )

    document_type = Column(
        String(100),
        nullable=True,
    )

    citation_count = Column(
        Integer,
        nullable=True,
    )

    # ---------------------------------------------------------
    # Keyword extraction tracking
    # ---------------------------------------------------------
    # Indicates where the saved keywords came from:
    #
    # "author" -> extracted from the PDF's keyword section
    # "yake"   -> generated automatically by YAKE
    # None     -> no keywords were found or generated

    keywords_source = Column(
        String(20),
        nullable=True,
    )

    # True when the keywords were generated by YAKE.
    # False when the keywords came from the author or are absent.

    keywords_generated = Column(
        Boolean,
        default=False,
        nullable=False,
    )

    # ---------------------------------------------------------
    # Validation tracking
    # ---------------------------------------------------------
    # A paper stays stored even if invalid.
    # This field only determines whether the paper can be used
    # by the Recommendation Layer.

    is_valid_for_recommendation = Column(
        Boolean,
        default=False,
        nullable=False,
        index=True,
    )
# Human-readable trace of what metadata_enrichment.py filled in and
    # from which source, e.g. "abstract <- semantic_scholar (confidence 0.76)".
    # Optional -- see scripts/migrate_add_enrichment_notes.py.
    missing_fields = Column(
        Text,
        nullable=True,
    )
    enrichment_notes = Column(
    Text,
    nullable=True,
)
   
    
    # Example:
    # "abstract, publication_year"

    # ---------------------------------------------------------
    # Upload provenance
    # ---------------------------------------------------------
    # Used by the PDF automatic extraction workflow.

    source_filename = Column(
        String(300),
        nullable=True,
    )
    # Original uploaded PDF filename.

    extraction_method = Column(
        String(20),
        nullable=True,
    )
    # Possible values:
    # "auto"   -> extracted from PDF
    # "manual" -> entered or corrected manually

    stored_path = Column(
        String(500),
        nullable=True,
    )
    # Example:
    # "papers/104.pdf"

    # ---------------------------------------------------------
    # Text preparation and recommendation vectors
    # ---------------------------------------------------------
    # prepared_text contains:
    #
    # Title + Abstract + Keywords
    #
    # It is normalized before being used by TF-IDF and SBERT.

    prepared_text = Column(
        Text,
        nullable=True,
    )

    tfidf_vector = Column(
        Text,
        nullable=True,
    )
    # JSON-encoded list[float].

    sbert_vector = Column(
        Text,
        nullable=True,
    )
    # JSON-encoded list[float].

    # ---------------------------------------------------------
    # Timestamps
    # ---------------------------------------------------------

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )

    # ---------------------------------------------------------
    # Relationships
    # ---------------------------------------------------------

    library_entries = relationship(
        "PersonalLibrary",
        back_populates="paper",
        cascade="all, delete-orphan",
    )

    def __repr__(self):
        return (
            f"<Paper id={self.id} "
            f"title={self.title[:40]!r}>"
        )


class PersonalLibrary(Base):
    __tablename__ = "personal_library"

    __table_args__ = (
        # A user can only save the same paper once.
        UniqueConstraint(
            "user_id",
            "paper_id",
            name="uq_user_paper",
        ),
    )

    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=False,
        index=True,
    )

    paper_id = Column(
        Integer,
        ForeignKey("papers.id"),
        nullable=False,
        index=True,
    )

    saved_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    user = relationship(
        "User",
        back_populates="library_entries",
    )

    paper = relationship(
        "Paper",
        back_populates="library_entries",
    )

    def __repr__(self):
        return (
            f"<PersonalLibrary "
            f"user_id={self.user_id} "
            f"paper_id={self.paper_id}>"
        )